name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        environments:
          - "ttgo-lora32-v21"

    runs-on: ubuntu-latest
    name: Build with PlatformIO
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install platformio
      - name: Extract ESP32 platform version from platformio.ini
        run: |
          ESP32_VERSION=$(grep 'esp32_platform\s*=' platformio.ini | cut -d'@' -f2 | tr -d '[:space:]')
          echo "ESP32_PLATFORM_VERSION=${ESP32_VERSION}" >> $GITHUB_ENV
      - name: Trigger framework installation
        run: platformio run -e esp32dev-all-test
      - name: Replace libbtdm_app.a file
        run: cp lib/esp32-bt-lib/esp32/libbtdm_app.a $HOME/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/ld/libbtdm_app.a
      - name: Verify file replacement
        run: |
          echo "Listing the file at the target location:"
          ls -ltr $HOME/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/ld/
          echo "Checking file checksum:"
          md5sum $HOME/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/ld/libbtdm_app.a
      - name: Run PlatformIO
        run: platformio run -e ${{ matrix.environments }}
      - name: Upload Assets
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.environments }}
          path: |
            .pio/build/*/firmware.bin
            .pio/build/*/partitions.bin
          retention-days: 7

  documentation:
    runs-on: ubuntu-latest
    name: Create the documentation
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - name: Install build dependencies
        run: npm install
      - name: Build documentation
        run: npm run docs:build
